# Artifex Analysis Options - Strict Linting Configuration
# Based on popular Flutter apps and Very Good Analysis standards

include: package:flutter_lints/flutter.yaml

analyzer:
  # Enable strict mode for stronger type checking
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  
  # Exclude generated files from analysis
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/generated/**"
    - build/**

linter:
  rules:
    # Critical Rules - These catch bugs and improve safety
    avoid_print: true
    avoid_web_libraries_in_flutter: true
    close_sinks: true
    diagnostic_describe_all_properties: false # Too verbose for our use case
    invariant_booleans: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_logic_in_create_state: true
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    use_key_in_widget_constructors: true
    
    # Performance Rules - Use const constructors and efficient patterns
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
    unnecessary_const: true
    use_colored_box: true
    use_decorated_box: true
    
    # Code Quality Rules - Make code more readable and maintainable
    always_use_package_imports: true
    annotate_overrides: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_redundant_argument_values: true
    avoid_return_types_on_setters: true
    avoid_unnecessary_containers: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_null_aware_operators: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    require_trailing_commas: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_rethrow_when_possible: true
    void_checks: true
    
    # Style Consistency (less aggressive than full strict mode)
    camel_case_extensions: true
    camel_case_types: true
    constant_identifier_names: true
    file_names: true
    flutter_style_todos: true
    non_constant_identifier_names: true
    package_names: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    
    # Type Safety and API Design
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    type_annotate_public_apis: true
    
    # Error Handling and Async Patterns
    avoid_catches_without_on_clauses: true
    avoid_void_async: true
    
    # Code Organization and Structure
    directives_ordering: true
    sort_constructors_first: true
    
    # Expression Style and Conciseness
    avoid_types_on_closure_parameters: true
    omit_local_variable_types: true
    prefer_expression_function_bodies: true
    prefer_final_locals: true
    unnecessary_lambdas: true
