// Mocks generated by Mockito 5.4.6 from annotations
// in artifex/test/features/photo_capture/presentation/providers/photo_capture_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:artifex/core/errors/failures.dart' as _i5;
import 'package:artifex/features/photo_capture/domain/entities/photo.dart'
    as _i6;
import 'package:artifex/features/photo_capture/domain/repositories/photo_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PhotoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotoRepository extends _i1.Mock implements _i3.PhotoRepository {
  MockPhotoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Photo>> capturePhoto() =>
      (super.noSuchMethod(
            Invocation.method(#capturePhoto, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Photo>>.value(
              _FakeEither_0<_i5.Failure, _i6.Photo>(
                this,
                Invocation.method(#capturePhoto, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Photo>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Photo>> pickImageFromGallery() =>
      (super.noSuchMethod(
            Invocation.method(#pickImageFromGallery, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Photo>>.value(
              _FakeEither_0<_i5.Failure, _i6.Photo>(
                this,
                Invocation.method(#pickImageFromGallery, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Photo>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Photo>>> getRecentPhotos({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentPhotos, [], {#limit: limit}),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Photo>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Photo>>(
                    this,
                    Invocation.method(#getRecentPhotos, [], {#limit: limit}),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Photo>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deletePhoto(String? photoId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePhoto, [photoId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deletePhoto, [photoId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Photo>> savePhoto(_i6.Photo? photo) =>
      (super.noSuchMethod(
            Invocation.method(#savePhoto, [photo]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Photo>>.value(
              _FakeEither_0<_i5.Failure, _i6.Photo>(
                this,
                Invocation.method(#savePhoto, [photo]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Photo>>);
}
